USE alx_book_store;
SELECT 
    COLUMN_NAME AS 'COLUMN',
    COLUMN_TYPE AS 'TYPE',
    IS_NULLABLE AS 'NULL',
    COLUMN_DEFAULT AS 'DEFAULT',
    COLUMN_KEY AS 'KEY',
    EXTRA AS 'EXTRA'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'books';
